---
title: "Peer Production Experience Report"
author: "Liz Seeley"
date: "5/4/2021"
output: html_document
bibliography: PPExperienceCites.json
csl: apa-6th-edition.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Austin Covaid: Theory versus Practice

Looking back on my experience contributing to Austin Covaid, two separate forms of volunteer participation emerge: emergency participation and regular participation. I began my work with Austin Covaid by engaging in emergency participation during the winter storms that devastated Texas in February 2021. Although the Covaid platform was still used to make requests, the digital coordinators temporarily discontinued using the platform to connect volunteers with these requests. Instead, they created a document using Google Sheets and gave volunteers the ability to choose for themselves which requests they wanted to fulfill. Meanwhile, volunteers and coordinators communicated in a busy 127-person Signal chat regarding any updates or issues. I spent 4 days after the storm fulfilling requests in this manner. Emergency participation was a way of fulfilling public services,  such as delivering potable water, that the City of Austin was unable to provide because of the storm. In *From Exchange to Contributions: Generalizing Peer Production into the Physical World*, Christian Siefkes explains that the size of the participant pool can a major determinant of efficacy within public service peer production organizations [@http://zotero.org/users/local/imQBT0Mt/items/Q3G6LJS9]. In a smaller organization (10,000 people or less), more participants means more choice in terms of the fulfillment of tasks, but also inherent problems coordinating all the tasks that an association wants to handle [@http://zotero.org/users/local/imQBT0Mt/items/Q3G6LJS9]. These problems were highly evident during emergency participation, with the abandonment of the Covaid platform for coordinating volunteers, the emergency onboarding of new leadership, and drastic decision-making [@http://zotero.org/users/local/imQBT0Mt/items/WRPYWIL2; @http://zotero.org/users/local/imQBT0Mt/items/9G7NC5HT; @http://zotero.org/users/local/imQBT0Mt/items/LGDW6M8C]. Since the storm, I have continued to participate as a volunteer, fulfilling requests as they are assigned to me through the Covaid platform.  

I felt significantly more motivated to contribute during emergency participation compared to regular participation. Acknowledging that Crowston and Fagnot’s discussion of motivation is based on a study of Wikimedia Editors and that that community is quite different from the one I participated in, their analysis of the differences between what motivates an initial contribution, a sustained contribution, and a meta-contribution can be applied to my experiences with Austin Covaid [@http://zotero.org/users/local/imQBT0Mt/items/9JTNJFNQ]. During emergency participation, which can be seen as a version of the initial contribution stage, the barriers for participation were lowered thanks to the abandonment of the Covaid platform, increasing the likelihood that I would participate in the community [@http://zotero.org/users/local/imQBT0Mt/items/9JTNJFNQ]. During regular participation, however, I did not completely share the motivations that drive what Crowston and Fagnot refer to as a sustained contributor. Sustained contributors are motivated by “the contributor’s feelings of obligation to the project, the intrinsic motivation of the task and feedback from the task and other participants” [@http://zotero.org/users/local/imQBT0Mt/items/9JTNJFNQ]. In the non-emergency state of Austin Covaid, someone submits a request, the digital coordinator receives and assigns the request, and the volunteer accepts and fulfills the request. Requesters do not need an account to make requests, and the volunteer can only view requests that have been directly assigned to them by a coordinator. Direct communication with other Austin Covaid participants only occurred when I ran into problems fulfilling a request. During the time I spent regularly participating, I viewed this lack of communication as a lack of feedback, leading me to feel disconnected to the other participants and less interested in contributing. Perhaps because of this, I never became anything resembling a meta-contributor within Austin Covaid [@http://zotero.org/users/local/imQBT0Mt/items/9JTNJFNQ].  

In part because of the lack of communication between participants, there were also few chances to move from one role to another, an aspect I found frustrating given that I hoped to get a more holistic experience of participation within the organization. However, despite my interest in doing other tasks within the community, my decision to only participate as a volunteer can also be interpreted as an unofficial form of as “task-auctioning” within Austin Covaid [@http://zotero.org/users/local/imQBT0Mt/items/Q3G6LJS9]. Task-auctioning describes instances in which it requires more of a commitment to do a more desirable task than to do a less desirable one. In terms of contributing as a requester, I do not possess, nor do I desire to possess, the level of material need insecurity that would motivate me to participate in the community. On the other hand, I would consider coordinators to be meta-contributors, according to Crowston and Fagnot- meaning, in other words, that being a coordinator is a much bigger commitment than just fulfilling a couple of requests every week [@http://zotero.org/users/local/imQBT0Mt/items/9JTNJFNQ; @http://zotero.org/users/local/imQBT0Mt/items/9G7NC5HT]. Working as a coordinator, although more appealing than volunteering because it does not require leaving the house, requires a day-long shift once a week and participation during leadership meetings. Therefore, through task-auctioning, I chose to maintain participation as a volunteer.  

There is no formal review process in place within Austin Covaid. In addition, the Covaid platform does not lend itself to informal review between the various user groups because it contains no features to allow participants to virtually communicate with each other. Any review process for participants’ contributions- creating requests, coordinating requests, and fulfilling requests- is passive and non-transparent. For example, for the requester participant group, digital coordinators review and edit the requests for clarity before assigning them to a volunteer, but the requesters do not see these edits [@http://zotero.org/users/local/imQBT0Mt/items/9G7NC5HT]. The only form of review for volunteers occurs when volunteers fail to accept and fulfill a request that they were assigned. During one busy weekend, I made this mistake, leaving the request in my queue. For a couple of weeks after, I noticed I was no longer being assigned requests by coordinators, assumedly because I had failed to fulfill the one in my queue, even though that request had been reassigned to someone else. I was only able to fix this by directly contacting a coordinator within the organization and clarifying my interest in continuing to participate. Review of work also occurs through the leadership meetings between the coordinators, where they discuss problems within the organization and offer solutions [@http://zotero.org/users/local/imQBT0Mt/items/LGDW6M8C]. However, the homophily within the leadership of Austin Covaid poses a risk to accurate internal review and unbiased decision making. Although the organization is quite diverse in terms of the volunteer and requester participants, the coordinators are all queer graduate students or young professionals in their mid to late twenties [@http://zotero.org/users/local/imQBT0Mt/items/9G7NC5HT]. The composition of voluntary groups induces homophily, with certain people gravitating towards those with similar identities [@http://zotero.org/users/local/imQBT0Mt/items/T373CFVU]. In a peer production community like Austin Covaid, the educational and age homophily within the governing participant group could lead to behavioral homophily, encouraging a lack of diversity in terms of perspectives and uniform decision-making [@http://zotero.org/users/local/imQBT0Mt/items/33E6L9TA].  

In my community identification and adaptation papers, I argued for Austin Covaid as a commons-based peer production community [@http://zotero.org/users/local/imQBT0Mt/items/789JT9DD; @http://zotero.org/users/local/imQBT0Mt/items/ZH4BABZ4; @http://zotero.org/users/local/imQBT0Mt/items/LGDW6M8C; @http://zotero.org/users/local/imQBT0Mt/items/2QDXD6X5]. After participating in the community, I maintain that Austin Covaid still qualifies as CBPP in terms of production. However, in terms of *community*, my expectations for participating in Austin Covaid differed greatly from my actual experience in terms of governance and transparency. I question whether Austin Covaid can truly be characterized as a non-hierarchical and decentralized community given the homophily within the governing members of the organization. While diverse motivations for participating exist across the organization, homophily often perpetuates itself, pointing to the lack of diversity in the Austin Covaid leadership group and the difficulty of entering into that group [@http://zotero.org/users/local/imQBT0Mt/items/T373CFVU]. In hindsight, I used Austin Covaid as my peer production community because I thought that choosing a newly formed, hybrid online/in-person organization, especially one where I personally knew a member of the leadership, would allow me to participate more intimately than in an entirely online peer production community with a huge user base. More importantly, I thought it would be easier for me to directly experience and contribute to the decision-making process. However, through my experiences participating in the community, the discussions on governance dynamics I had with my contact in the organization, and multiple failed attempts to contribute, or observe the contributions, of the coordinators, I discovered that the non-hierarchical, transparency touted by my digital coordinator contact, while perhaps non-hierarchical and transparent between the coordinators themselves, was not the case for the Austin Covaid peer production community overall.  

## References (APA 6th Edition)
