---
title: "PP Experience Report"
author: "Alexander Reese"
date: "5/3/2021"
output: 
  html_document:
    theme: cerulean
bibliography: bibliography.bib
csl: apa-7th-edition.csl
---

Peer Production -- INF 385T

Professor James Howison


The first step in contributing to the Standard Ebooks (SE) project involved messaging the mailing list with a "First project" proposal. I had originally planned starting with W. E. B. DuBois' *The Souls of Black Folks,* but after perusing the Manual of Style and some pages scans of an early editions, I realized it was a long text that contained a lot of semantic complexity -- poems, music, and illustrations that I would need to render as vector graphics. For these reasons, it also stood a good chance of getting rejected as a first project by community leadership. Not wanting to rock the boat or bite off more than I could chew, I turned to a much shorter and less complex novel, Willa Cather's *O Pioneers!* As part of my project proposal, to the mailing list, I identified a transcription created by [Project Gutenberg](https://www.gutenberg.org/ebooks/24) and Public Domain scans of a first 1913 edition at the [HathiTrust](https://babel.hathitrust.org/cgi/pt?id=mdp.39015005089597) that I would reference when proofreading and marking up the text.

Even drafting my very short proposal email, I anxiously referred to other "First project" messages on the mailing list and read through replies from the editor-in-chief to know how to frame my proposal and what kind of replies to expect or avoid. The project was readily approved by the editor-in-chief, who sent a boilerplate response linked me to documentation and new contributor resources. However, he also included several formatting tips and considerations specific to my book project which gave the response a personal touch and made me feel supported and engaged with. And importantly, he encouraged me to reach out frequently with questions.

I familiarized myself with the [The Standard Ebooks Manual of Style](https://standardebooks.org/manual/1.5.0/single-page)and followed first-time contributor guide, making a regular rhythm of commits. The [Standard Ebooks toolset](https://github.com/standardebooks/tools) automates much of the process of creating a structured file directory, adjusting typography, modernizing spelling, formatting the files, etc., but detailed semantic markup requires human intervention. The novel contains several instances of verse, songs, letters, and foreign languages that required I learn project markup standards. The Manual of Style was helpful in this process but being able to look at the markup of existing ebook projects was indispensable. To do this, I learned how to search GitHub repositories for specific instances of code/text. Thankfully, someone had already contributed a Cather novel (*My Ántonia*) which had similar metadata, file structure, and included many of the same semantic elements.

Over the course of this first project, I encountered several confusing issues with semantic markup and my ebook's file structure, but I did not end up reaching out to the mailing list with any questions. Every time I had what I thought had a valid question to pose, I found my own answer or solution by looking through existing ebooks. I drafted and deleted several emails this way. I knew there was value in posing questions -- it communicated active work, critical thought, concern and attention to detail -- but I was also wary of appearing stupid or annoying with silly questions. Having read Eric Raymond and Rick Moen's piece "How To Ask Questions The Smart Way," I did not want to appear "unwilling to think or to do [my] own homework" or to waste anyone's time or goodwill [@raymond_how_2014]. I did however get a chance to interact with project leaders when proposing cover art, and I will again when I finish proofreading and submit my ebook for review.

I agonized a bit over the cover art, not wanting to have my suggestions rejected. Interestingly, the cover art was more a matter and expression of taste than technical skill, which I have not seen addressed by any literature on open collaboration. I found it difficult to find public domain oil paintings (the community standard) of American prairie life. My favorite works by regionalist painters (Harvey Dunn or Grant Wood) were sometimes just a handful of years too young to be in the public domain. Others hadn't been digitized at a high enough quality. In the end I threw out three different ideas, to increase my chances of approval (but not too many so as to burden the editors). Again, I referred to lots of other emails proposing cover art, to learn what things might be rejected (watercolors, generic or "dime-a-dozen" imagery). Even with this due diligence, I still managed to make a mistake. To my surprise, the editor-in-chief told me the links I had shared were not sufficient to prove the public domain status of the works, and I had to go hunting around for a reproduction of the painting in a book published before 1925. I felt more than a little embarrassed by my mistake, but some diligent internet sleuthing produced a reproduction in a 1918 *Art in America*, which the editor called "excellent" before thanking me, assuaging my insecurities.

As one of the final steps in preparing my ebook, I was invited to add my name and personal website to the metadata and colophon as the book's "producer," which was exciting and lead me to recognize it as an incentive for participation and contribution. Though is not necessarily the kind of exciting complicated work or robust crediting system that will overly influence my career, even this small instance of self-promotion felt like a reward and made me want to keep contributing in order to build a portfolio of work. Importantly, credit is also given to the original transcribers cited on the book's Project Gutenberg page and future proofreaders who make edits to the text. This makes possible the visibility of contributions and shared claims to reputation (in contrast to academic open software development and publishing) [@howison_incentives_2013].

Having read Fogel's chapter on managing participants, it was easy to see how many managerial techniques were applied by the editors -- delegating tasks like book reviewing, redirecting contributors away from certain artwork or projects, referring contributors to documentation, expressing appreciation, etc. [@fogel_producing_2009]. However, it was strange to be on the receiving end of these techniques; I almost resented it at times. This perspective made it so clear who was in charge and how little influence I had. The editor-in-chief was as classic benevolent dictator, calling a lot of shots and having final say in many decisions, while I was simply a contributor to be managed.

Given the independent nature of ebook production, the SE project at first struck me as characterize by significant autonomy, which is thought to enhance one's intrinsic motivations [@ryan_intrinsic_2000]. However, I quickly came to feel like the project was actually fairly rigid and controlled. There is flexibility in *when* and *how* you work, but the Manual of Style lays out very clear rights and wrongs. Editors communicate that there is usually one right way to format and structure a text, and when there isn't a pre-existing rule, direction often comes from the top down. In this way, SE leadership toes an uncertain line between coordination and control [@benkler_peer_2016], sometimes relying more on planning and hierarchy than adaptability, which stands in contrast to FLOSS projects [@kelty_two_2008]. Put differently, while contributors can self-assign tasks by choosing their own ebook projects, the tasks themselves can feel somewhat controlled and prescribed. In this way, task conception is perhaps not as decentralized as in Benkler's model of commons-based peer production and at times resembles that of crowdsourcing [@benkler_peer_2016]. I admit that this view may be overly colored by my perspective as a first-time contributor still learning the community's standards and norms. I am only an ebook novice without much "wisdom" to contribute yet [@kittur_harnessing_2008]. I imagine as one contributes more and more, and builds a reputation as skillful and insightful to the formatting and semantic challenges posed my complex projects, they are given more leeway to respond to complexities, novel issues, and questions of style.

### References
